(ns lipas-api.property-types
  (:require [lipas-api.util :refer [locale-key]]))

(defn format-prop-type
  [prop locale]
  (hash-map
   (keyword (:handle-en prop)) {:name ((locale-key :name locale) prop)
                                :description ((locale-key :description locale) prop)
                                :dataType (:data-type prop)}))

(def prop-type-keys
  [:liftsCount
   :boxingRingsCount
   :floorballFieldsCount
   :pistolShooting
   :shotputCount
   :swimmingPoolCount
   :pool1TemperatureC
   :7m5PlatformsCount
   :equipmentRental
   :ligthing
   :kiosk
   :fieldsCount
   :kPoint
   :skiService
   :fieldLengthM
   :showJumping
   :cosmicBowling
   :field3AreaM2
   :polevaultPlacesCount
   :spinningHall
   :waterslidesTotalLengthM
   :climbingWall
   :iceClimbing
   :sauna
   :trackWidthM
   :routeWidthM
   :basketballFieldsCount
   :pier
   :10mPlatformsCount
   :pool4TemperatureC
   :bowlingLanesCount
   :squashCourtsCount
   :altitudeDifference
   :gymnasticsSpace
   :climbingWallWidthM
   :shower
   :pool5LengthM
   :skijumpHillMaterial
   :summerUsage
   :hammerThrowPlacesCount
   :parkingPlace
   :trackLengthM
   :climbingRoutesCount
   :field3WidthM
   :skiTrackTraditional
   :litSlopesCount
   :coveredStandPersonCount
   :surfaceMaterial
   :iceReduction
   :pool1MaxDepthM
   :poolWaterAreaM2
   :shortestSlopeM
   :badmintonCourtsCount
   :green
   :5mPlatformsCount
   :fieldWidthM
   :pool5WidthM
   :accessibilityInfo
   :trainingWall
   :lightRoof
   :3mPlatformsCount
   :basketballFieldType
   :pool5MinDepthM
   :pool4MinDepthM
   :javelinThrowPlacesCount
   :waterSlidesCount
   :field1LengthM
   :areaKm2
   :airGunShooting
   :skiTrackFreestyle
   :jumpsCount
   :pool1LengthMM
   :automatedTiming
   :surfaceMaterialInfo
   :pool5MaxDepthM
   :pool2LengthM
   :weightLiftingSpotsCount
   :euBeach
   :infoFi
   :pool3TracksCount
   :snowparkOrStreet
   :restPlacesCount
   :playground
   :pool2MinDepthM
   :longjumpPlacesCount
   :tatamisCount
   :holesCount
   :halfpipeCount
   :beachLengthM
   :handballFieldsCount
   :matchClock
   :sprintLanesCount
   :exerciseMachinesCount
   :pool5TemperatureC
   :wrestlingMatsCount
   :volleyballFieldsCount
   :tennisCourtsCount
   :mayBeShownInExcursionMapFi
   :pool3WidthM
   :trainingSpotSurfaceMaterial
   :longestSlopeM
   :heightM
   :toilet
   :shotgunShooting
   :curlingLanesCount
   :pool3LengthM
   :climbingWallHeightM
   :pool2TracksCount
   :litRouteLengthKm
   :changingRooms
   :pool3MinDepthM
   :groupExerciseRoomsCount
   :maxVerticalDifference
   :futsalFieldsCount
   :automatedScoring
   :innerLaneLengthM
   :pool5TracksCount
   :field1WidthM
   :pool4WidthM
   :landingPlacesCount
   :pool4MaxDepthM
   :sprintTrackLengthM
   :footballFieldsCount
   :otherPoolsCount
   :pool1TracksCount
   :gymnasticRoutinesCount
   :shootingPositionsCount
   :freestyleSlope
   :1mPlatformsCount
   :scoreboard
   :pool1WidthM
   :rifleShooting
   :finishLineCamera
   :pool3TemperatureC
   :runningTrackSurfaceMaterial
   :field1AreaM2
   :circularLanesCount
   :standCapacityPerson
   :discusThrowPlaces
   :pPoint
   :field2LengthM
   :tableTennisCount
   :boatPlacesCount
   :field2AreaM2
   :otherPlatforms
   :iceRinksCount
   :boatLaunchingSpot
   :pool4TracksCount
   :tobogganRun
   :field2WidthM
   :areaM2
   :pool3MaxDepthM
   :trackType
   :routeLengthKm
   :loudspeakers
   :pool2MaxDepthM
   :outdoorExerciseMachines
   :pool4LengthM
   :slopesCount
   :field3LengthM
   :fencingBasesCount
   :pool2TemperatureC
   :heating
   :winterUsage
   :plasticOutrun
   :highjumpPlacesCount
   :freeRifleShooting
   :range
   :pool1MinDepthM
   :inrunsMaterial
   :skijumpHillType
   :mayBeShownInHarrastuspassiFi
   :pool2WidthM
   :padelCourtsCount])
