#!/bin/bash

set -e

psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -c "DROP DATABASE IF EXISTS $DB_NAME;"
psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -c "DROP USER IF EXISTS $DB_USER;"
psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -c "CREATE USER $DB_USER WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION PASSWORD '$DB_PASSWORD';"
psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -c "CREATE DATABASE $DB_NAME WITH OWNER=$DB_USER ENCODING='utf-8;'"
psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -d $DB_NAME -c "CREATE EXTENSION postgis"
psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -d $DB_NAME -c "CREATE EXTENSION postgis_topology"
