#!/bin/bash

set -e

psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER <<EOF
     DROP DATABASE IF EXISTS $DB_NAME;
     DROP USER IF EXISTS $DB_USER;
     CREATE USER $DB_USER WITH
            LOGIN
            REPLICATION
            PASSWORD '$DB_PASSWORD';
     CREATE DATABASE $DB_NAME WITH OWNER=$DB_USER ENCODING='utf-8';
EOF

psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -d $DB_NAME <<EOF
     CREATE EXTENSION postgis;
     CREATE EXTENSION postgis_topology
EOF
