#!/bin/bash

set -e

psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER <<EOF
     DROP DATABASE IF EXISTS $AUTH_DB_NAME;
     DROP USER IF EXISTS $AUTH_DB_USER;
     CREATE USER $AUTH_DB_USER WITH
            LOGIN
            PASSWORD '$AUTH_DB_PASSWORD';
     CREATE DATABASE $AUTH_DB_NAME WITH OWNER=$AUTH_DB_USER ENCODING='utf-8';
     GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB_NAME to $AUTH_DB_USER;
EOF

psql -h $DB_HOST -p $DB_PORT -U $DB_SUPERUSER -d $AUTH_DB_NAME <<EOF
     CREATE EXTENSION IF NOT EXISTS citext;
     CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOF
