-- Table: wfs.gt_pk_metadata
-- GeoServer primary key metadata table for materialized views
-- Enables stable feature IDs and WFS pagination for views/materialized views
-- See: https://docs.geoserver.org/stable/en/user/data/database/primarykey.html

CREATE TABLE IF NOT EXISTS wfs.gt_pk_metadata
(
    table_schema TEXT NOT NULL,
    table_name TEXT NOT NULL,
    pk_column TEXT NOT NULL,
    pk_column_idx INTEGER,
    pk_policy TEXT,
    pk_sequence TEXT,
    CONSTRAINT gt_pk_metadata_unique UNIQUE (table_schema, table_name, pk_column),
    CONSTRAINT gt_pk_metadata_policy_check CHECK (pk_policy IN ('sequence', 'assigned', 'autogenerated'))
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS wfs.gt_pk_metadata
    OWNER to lipas;

--;;

CREATE INDEX IF NOT EXISTS idx_gt_pk_metadata_lookup
    ON wfs.gt_pk_metadata(table_schema, table_name);
