name: dev deployment

on:
  workflow_dispatch:
  push:
    branches:
        - deployment-scripts

jobs:
  deployment:
    runs-on: self-hosted
    environment: dev
    steps:
      - run: pwd
      - run: whoami
      - run: ls -larth
